//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid QuestionId { get; set; }
        public System.DateTime AnswerDate { get; set; }
        public string Text { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Question Question { get; set; }
    }
}
